title: Your awesome title
author: GitHub User
email: your-email@domain.com
title: my page
date: 2022-02-03
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 AWESOME AWESOME.
  

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
